
"""
    test_samples(samples::Matrix{Float64}, mass_balance, balance, lbs, ubs)

Test if `samples` generated by some sampling algorithm, e.g. `hit_and_run`, are
consitent with the model's constraints. That is, if the `mass balances` and flux bound
constraints (`ubs`, `lbs`) are satisfied. Returns a vector of indices where the
constraints are violated. 
"""
function test_samples(samples::Matrix{Float64}, mass_balance, balance, lbs, ubs)
    violations = Int[]
    tol = 1e-6
    for i = 1:size(samples, 2)
        if isapprox(mass_balance * samples[:, i], balance; atol = tol)
            equality = true
        else
            equality = false
        end
        inequality =
            all(abs.(lbs .- samples[:, i]) .<= tol) .==
            all(abs.(samples[:, i] .- ubs) .<= tol)
        if !all([equality, inequality])
            push!(violations, i)
        end
    end

    return violations
end
